### PR TITLE
GH601: Enable snupkg symbol packages

### PR DESCRIPTION
**Pull request by gitfool**
Following up from #601.

### CODE REVIEW

**Comment by gitfool** [comment]
Downloading AppVeyor [39079294](https://ci.appveyor.com/project/kroniak/flurl/builds/39079294/artifacts) artifacts:

`Flurl.3.0.2.nupkg`:
image

`Flurl.3.0.2.snupkg`:
image

**Comment by tmenier** [comment]
Given that it's been a full year since you opened this (yikes...sorry!) can I assume this is still necessary in .NET 6 and still the most modern/recommended way of doing this? Also is it safe to assume it won't adversely affect anyone's dev experience? I'm about to start on 4.0 and wondering if this should go in the final 3.x maintenance release or the first 4.0 prerelease.

As I mentioned in #601, this isn't my area of expertise so I'm going to trust your judgement here. Thanks! :)

**Comment by gitfool** [comment]
Yes, I _think_ the issue I mention in https://github.com/tmenier/Flurl/issues/601#issuecomment-835926920 is only going to be addressed in the dotnet 7 sdk. That and publishing a separate `snupkg` _seems_ to be the recommended way now. 😅

If you want to publish a maintenance release with this change then I'll make sure to confirm that I can still step debug with it.

**Comment by tmenier** [comment]
I was hoping I could get this published quickly so you could test it but it looks like the snupkg needs to be uploaded separately and I have no idea where to do that. I'll let you know when I figure that out.

**Comment by gitfool** [comment]
How are you publishing now? IIRC, it should just work given the changes I made...

**Comment by gitfool** [comment]
Using what command? That command should handle uploading the `snupkg` too.

**Comment by tmenier** [comment]
Using the web site. I publish the packages manually and I don't see a place to upload a symbols package.

**Comment by tmenier** [comment]
Doh...I stand corrected - you can totally do it from the web UI. Same upload box even. Don't know how I missed that! I'm getting this (pre)released now.

I know my processes could use improving and I'd love to move off of AppVeyor and on to GH Actions, then automate releases. But like with so many things I just haven't had the time.

**Pull request merged**
