### PR TITLE
simple encoding fix

### PR DESCRIPTION
**Pull request by engenb**
Going to start out by saying I don't think this PR in it's current state is the solution, but more the start of a conversation around a problem.

Here's the problem:

I'm using Flurl.Http to hit a web api that's returning responses with

```Content-Type: text/javascript; charset="UTF-8"```

Notice the charset value surrounded with quotes, which is legal according to this section of the [W3C spec](http://tools.ietf.org/html/rfc7231#section-3.1.1.5).  However, HttpClient is choking on the charset value because it is surrounded with quotes.  ```HttpContent.ReadAsStringAsync()``` uses the Content-Type header's charset value (if present) to determine the encoding to use, but it does not guard itself against the charset value being quoted and throws an exception.  Here's a simple [fiddle](https://dotnetfiddle.net/bNxJAS) of this in action.

I realize this isn't a problem with Flurl.  It is actually a problem with ```HttpContent.ReadAsStringAsync()``` which Flurl uses quite a bit.  Unfortunately, I can't simply submit a PR to the team that maintains ```System.Net.Http```

If HttpClient isn't going to to properly handle different valid charset schemes, I propose we handle it - do you agree?  A few solutions to this:

1. put in the quick fix from this changeset
2. add an extension method on ```Task<HttpResponseMessage>``` that does this work, and potentially handle other gotchas like this
3. add a callback hook like those provided in ```FlurlHttp.Configure``` to give the implementer (like me) access to the ```HttpResponseMessage``` after ```SendAsync``` but before things like ```HttpResponseMessageExtension.ReceiveString``` to allow for "data massaging" like this

I'm leaning towards option 2 as an aggregate extension method like ```ProcessResponse``` that delegates to specific extensions like ```StripCharsetQuotes``` as well as whatever other gotchas come up in the future.

Please let me know your thoughts on the subject and if you like any of options 1-3 or even a 4th option I didn't think of.  I'd be happy to help implement a more robust solution to this problem through this PR depending on what you think fits best for the project.

Thanks!

### CODE REVIEW

**Comment by tmenier** [comment]
Thanks for the PR and helpful explanation. This is indeed a bug with HttpClient and is on the CoreFX RTM roadmap:

https://github.com/dotnet/corefx/issues/5014

So to your point, what to do about it in the mean time? I have to think this is obscure as it's never come up before. Mind if I ask what API this is and if there's any chance they'd consider dropping the quotes?

Let's assume not. I think I'm inclined to accept your PR. I'm hesitant to fix it via hooks or extensions because it's about fixing a glitch in the implementation of the HTTP spec, rather than providing custom behavior. For this and anything similar down the road, I'm good with baking it in directly.

There's 2 changes that I think would be ideal:

1. Since the bug is specific to `ReadAsStringAsync`, could we fix it a little closer to the metal? In other words, just in the places that use it? (I wouldn't say Flurl uses it all over - 2 places from what I can see. :))

2. Could we demonstrate the fix with a unit test?

I'd be happy to take on both of these and package up a new release. If you need it sooner (I will try to get to it very soon), have you considered just an extension method in your project? I think you'd just want a replacement for `ReceiveString` and possibly `GetStringAsync`, both one-line extension methods.

**Comment by engenb** [comment]
oh wow that's right, they open sourced .net core! 

I actually have created an extension method in my project to strip the quotes, and there's definitely no rush on this.

The api I'm hitting is [PubNub](https://www.pubnub.com/).  I put out a request to them as well to consider dropping the quotes, but no movement on that yet.

I can definitely look at moving this to the specific places it's needed.  And I will absolutely add some tests.  I typically subscribe to full-on TDD - just didn't here because I kinda figured the initial example fix would be throwaway.

**Comment by tmenier** [comment]
Thanks! I'm pretty far from full-on test-first. I've finally gotten better about test-sometime though. Baby steps :)

**Comment by tmenier** [comment]
Finally getting back to this one. I like your implementation but I'm going to merge it manually. httpbin.org has a slick way to test this so I'm going to test it differently, plus I want it in the dev branch. It'll get released with Flurl.Http 1.0, hopefully fairly soon.

**Comment by tmenier** [comment]
Prerelase containing this fix is now available:

https://www.nuget.org/packages/Flurl.Http/1.0.0-beta7

Please test and provide any feedback.

**Comment by tmenier** [comment]
Closing the PR since I sort of merged some of your bits manually. 1.0 will be out of beta soon.

**Comment by karelz** [comment]
@engenb

> Unfortunately, I can't simply submit a PR to the team that maintains System.Net.Http

I wonder why you feel/felt that way (actually @CIPop just told me that was the situation back in May - sorry for that) ... Now we are actually taking community contributions to CoreFX. We sadly are a bit behind on triage (yeah, some issues are 1+ year old), but we got much better over the last few months, so if you find something that bugs you, feel free to jump in (assuming it is no breaking change, or change in the wrong direction, etc. - the usual stuff ...).

**Pull request closed without merging**
