### PR TITLE
Updated the HttpTest to use a ConcurrentQueue<T>

### PR DESCRIPTION
**Pull request by TheAllSeeingPie**
Updated the HttpTest to use a ConcurrentQueue<T> and removed the superfluous setter. Because of the change of API this would have been a breaking change to existing tests that used to set a Queue<T> so it seems like a good chance to remove it and ensure people populate the response queue using API requests and not pre-built queues.

Fixes: https://github.com/tmenier/Flurl/issues/366
Fixes: https://github.com/tmenier/Flurl/issues/398

### CODE REVIEW

**Comment by TheAllSeeingPie** [comment]
Hey @tmenier, any chance this could get reviewed please? Would really help out something I'm working on.

**Comment by tmenier** [comment]
Sorry, it looks good but I'm not going to release it until 3.0 because it's a breaking change.

**Comment by TheAllSeeingPie** [comment]
@tmenier that's fair enough, thanks for responding!

**Comment by tmenier** [comment]
Thanks again. Just FYI, I'm releasing new 3.0 features in a series of prerelases. This one will go out next. I'm considering these stable for product use, just not guaranteeing I won't make additional breaking changes before the official 3.0. So if you can live with that, you'll have this very soon.

**Comment by tmenier** [comment]
Well, that `ConcurrentQueue` might be very short lived. I didn't think about the implications of #481, which is next up. It'll need to select responses based on pattern matching, so simply grabbing the first item off the queue is out. I might be able to pull it off with a list of `ConcurrentQueue`s, otherwise I may need to resort to locks. I'll play around with it and see what works best. I've got a good test in place anyway.

**Pull request merged**
