### PR TITLE
Return back full PCL

### PR DESCRIPTION
**Pull request by kroniak**
Need to merge and upload to nuget after testing by @tylerlong.
#118 #119

### CODE REVIEW

**Comment by kroniak** [comment]
@tmenier where is build? AppVeyor disconnected?

**Comment by tmenier** [comment]
I don't think anything's disconnected, unless it was earlier and fixed itself. Build succeeded though - thanks!

I wonder, is there any way to point the shields.io appveyor badge at the latest _master_ build specifically? I don't love that on the main Flurl page it shows build failing when master is fine. Probably not a big deal though, normally we take care to make sure it's always passing or fix it right away.

**Comment by kroniak** [comment]
@tmenier  https://github.com/tmenier/Flurl/commit/3b36293f7f9b8971f9ccd217e6cbeb7c135ad5a6

**Comment by tmenier** [comment]
you sir are amazing.

**Pull request merged**
