### PR TITLE
Initial support for dotnetcore

### LINKED ISSUE #61: Support for .NET Core
Are there any plans to support .net core? I'm using Flurl.Http with ASP.NET 5 and it says Flurl does not support DnxCore5.0

### PR DESCRIPTION
**Pull request by eByte23**
Fixes #61 
Greater refactoring could be done to merge all projects into see NewtonsoftJson project for details on targeting multiplatform support.

### CODE REVIEW

**Comment by tmenier** [comment]
I've been on vacation so haven't had a chance to dig into this, but at a glance I will say that I probably won't merge it if it's largely duplicated code. I used shared projects in order to support multiple platforms without code duplication. If you're able to refactor to that pattern that'd be great, otherwise I'll take a crack at it when I have some time. Thanks again for the contribution.

**Comment by eByte23** [comment]
I should have sometime tomorrow will give it a go.
Did you want to implement async methods or just keep them sync? As now would be a decent time to do it.

**Comment by kroniak** [comment]
Please review #64

**Comment by kroniak** [comment]
Please close

**Pull request closed without merging**
