### PR TITLE
GH513: Enable SourceLink with embedded PDB

### LINKED ISSUE #513: Add SourceLink support
[SourceLink](https://github.com/dotnet/sourcelink) is standard now and would make it easy to debug code using this awesome package!

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #513.

### CODE REVIEW

**Comment by gitfool** [comment]
@tmenier PTAL; I'd love to get this merged for the next [pre]release. 😁

**Comment by tmenier** [comment]
Thanks for the reminder. Admittedly I'm not fully up to speed on SourceLink but [this](https://github.com/dotnet/sourcelink#alternative-pdb-distribution) is a little bit of a concern:

> Including PDBs in the .nupkg is generally no longer recommended as it increases the size of the package and thus restore time for projects that consume your package, regardless of whether the user needs to debug through the source code of your library or not.

They recommend publishing a separate symbol package to NuGet instead. What do you think about going that route?

**Comment by gitfool** [comment]
>They recommend publishing a separate symbol package to NuGet instead. What do you think about going that route?

Ultimately it comes down personal preference, but I'd advise to keep it simple and embed the PDB. I wouldn't be concerned at all since _portable_ PDBs are small, and combined with SourceLink they are tiny, so I always embed them.

To prove the above assertion, I rebased this PR and the generated `nupkg` files are composed as follows:

image
image

You'd save ~15KB and ~40KB respectively; hardly anything to be concerned about and, frankly, you'd save just as many KBs and be better off by dropping unsupported target frameworks.

**Comment by gitfool** [comment]
I threw in a couple of other tweaks:
* Fix test warning due to redundant use of `async Task`
* Use Visual Studio 2019 image on AppVeyor for latest 3.1.3xx+ dotnet sdk
  * ... fixes a [small issue](https://github.com/dotnet/sourcelink/issues/572#issuecomment-583548551) with the build order when embedding untracked sources

**Comment by tmenier** [comment]
Sounds good. You've talked me into it. :)

**Pull request merged**
