### PR TITLE
Add Microsoft.VisualStudio.Threading.Analyzers to catch potential deadlocks

### PR DESCRIPTION
**Pull request by hanabi1224**
Microsoft.VisualStudio.Threading.Analyzers is a great code analyzer to catch potential bugs (e.g. deadlock) around threading

### CODE REVIEW

**Comment by tmenier** [comment]
Did this analyzer catch any issues? I'm not familiar with how to use it. Again, I prefer to start with an issue, but at least this PR is cleaner and more single-purpose than #388 :)

**Comment by hanabi1224** [comment]
@tmenier  here're docs of all CA rules: https://github.com/Microsoft/vs-threading/tree/master/doc/analyzers

Some are quite useful, e.g. 
VSTHRD002: Synchronously waiting on Task, ValueTask, or awaiters is dangerous and may cause dead locks.
VSTHRD003 Avoid awaiting foreign Tasks
VSTHRD011 Use AsyncLazy<T>

**Comment by tmenier** [comment]
@kroniak If you have a chance could you give me your thoughts on this PR? There was never a discussion about adding this and I'm not sure I see a lot of value in it. Unless you feel differently, I might close it.

**Comment by kroniak** [comment]
Hello.

I will look this PR.
пт, 25 янв. 2019 г. в 22:13, Todd Menier <notifications@github.com>:

**Pull request closed without merging**
