### PR TITLE
Refactoring - PART 1 - Net core rc2

### LINKED ISSUE #85: Bug in parallel testing download file
When tests are running in parallel there are IO exceptions in method can_download_file.

Trick to avoid:

```c#
#if NETSTD
		[Test]
		public async Task can_download_file() {
			var path = await "http://www.google.com".DownloadFileAsync(@"c:\a\b", "google.txt");
			Assert.AreEqual(@"c:\a\b\google.txt", path);
			Assert.That(File.Exists(path));
			File.Delete(path);
			Directory.Delete(@"c:\a", true);
		}
#elif PORTABLE
		[Test]
		public async Task can_download_file()
		{
			var path = await "http://www.google.com".DownloadFileAsync(@"c:\b\a", "google.txt");
			Assert.AreEqual(@"c:\b\a\google.txt", path);
			Assert.That(File.Exists(path));
			File.Delete(path);
			Directory.Delete(@"c:\b", true);
		}
#endif
```

Will be added to last PR.

### PR DESCRIPTION
**Pull request by kroniak**
This is first big part of my refactoring to 1.0.0 version - update to RC2. #82 

Changes to **dev** branch:

- Added appveyor config - all is ready, waiting to enable a webhook. #83 
- Added badges to readme #83 
- Created [Flurl feed](https://www.myget.org/feed/Packages/flurl) on myget to fast upload test nuget packages and updated nuget.config. @tmenier I am waiting from you account details to add to owners on the feed.
- All source projects csproject -> xproject and moved to ./src
- All xproj updated to RC2.
- Flurl --> Flurl.Library xproject
- Flurl.Http.Net45 and Flurl.Http.PCL --> Flurl.Http.Library xproject
- Flurl.CodeGen --> xproject
- Added build scripts (./build) for cross-platform build without VS. I am using the VSCode also. This scripts and others are used in AppVeyor building also.
- nuspec and targets in projects updated to really world targets. View nuspecs. This is testing now. #43 #79 
- Fix #85 
- Bump all dependencies versions

Clone and look net_core_rc2_full branch. Play with it. I will tell what you want about this.

### CODE REVIEW

**Comment by morrisonbrett** [comment]
Can you please publish the MyGet feed URL and make it publicly accessible?

**Comment by kroniak** [comment]
@morrisonbrett It is public. 
```xml
<add key="flurl feed" value="https://www.myget.org/F/flurl/api/v3/index.json" />
```

**Comment by morrisonbrett** [comment]
Thanks @kroniak.  I have it working well on Windows, but now I'm seeing:

`vm-osx:BlackVueDownloader morrison$ dotnet test BlackVueDownloader.Tests/
Project BlackVueDownloader.PCL (.NETStandard,Version=v1.5) will be compiled because inputs were modified
Compiling BlackVueDownloader.PCL for .NETStandard,Version=v1.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.5543676
Project BlackVueDownloader.Tests (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling BlackVueDownloader.Tests for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.3062243
 

xUnit.net Runner (64-bit osx.10.10-x64)
  Discovering: BlackVueDownloader.Tests
  Discovered:  BlackVueDownloader.Tests
  Starting:    BlackVueDownloader.Tests
File exists Record/ignorefile.mp4, ignoring
    BlackVueDownloader.Tests.BlackVueDownloaderTests.InvalidResponseTest(ip: "192.168.1.1") [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
      ---- System.EntryPointNotFoundException : Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
      Stack Trace:
           at System.Net.Http.CurlHandler..ctor()
           at Flurl.Http.Configuration.FlurlHttpSettings.ResetDefaults()
           at Flurl.Http.FlurlHttp.<>c.<.cctor>b__7_0()
           at System.Lazy`1.CreateValue()
           at System.Lazy`1.LazyInitValue()
           at Flurl.Http.FlurlHttp.Configure(Action`1 configAction)
           at Flurl.Http.Testing.HttpTest..ctor()
           at BlackVueDownloader.Tests.BlackVueDownloaderTests.InvalidResponseTest(String ip)
        ----- Inner Stack Trace -----
           at Interop.Http.GetSupportedFeatures()
           at System.Net.Http.CurlHandler..cctor()
    BlackVueDownloader.Tests.BlackVueDownloaderTests.EmptyResponseTest(ip: "192.168.1.1") [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
      ---- System.EntryPointNotFoundException : Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
      Stack Trace:
           at System.Net.Http.CurlHandler..ctor()
           at Flurl.Http.Configuration.FlurlHttpSettings.ResetDefaults()
           at Flurl.Http.FlurlHttp.<>c.<.cctor>b__7_0()
           at System.Lazy`1.CreateValue()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Lazy`1.get_Value()
           at Flurl.Http.FlurlHttp.Configure(Action`1 configAction)
           at Flurl.Http.Testing.HttpTest..ctor()
           at BlackVueDownloader.Tests.BlackVueDownloaderTests.EmptyResponseTest(String ip)
        ----- Inner Stack Trace -----
           at Interop.Http.GetSupportedFeatures()
           at System.Net.Http.CurlHandler..cctor()
    BlackVueDownloader.Tests.BlackVueDownloaderTests.QueryCameraForFileListTest(ip: "192.168.1.1") [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
      ---- System.EntryPointNotFoundException : Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
      Stack Trace:
           at System.Net.Http.CurlHandler..ctor()
           at Flurl.Http.Configuration.FlurlHttpSettings.ResetDefaults()
           at Flurl.Http.FlurlHttp.<>c.<.cctor>b__7_0()
           at System.Lazy`1.CreateValue()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Lazy`1.get_Value()
           at Flurl.Http.FlurlHttp.Configure(Action`1 configAction)
           at Flurl.Http.Testing.HttpTest..ctor()
           at BlackVueDownloader.Tests.BlackVueDownloaderTests.QueryCameraForFileListTest(String ip)
        ----- Inner Stack Trace -----
           at Interop.Http.GetSupportedFeatures()
           at System.Net.Http.CurlHandler..cctor()
    BlackVueDownloader.Tests.BlackVueDownloaderTests.GetListOfFilesAndProcessTest(ip: "192.168.1.99", numRecords: 10) [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
      ---- System.EntryPointNotFoundException : Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
      Stack Trace:
           at System.Net.Http.CurlHandler..ctor()
           at Flurl.Http.Configuration.FlurlHttpSettings.ResetDefaults()
           at Flurl.Http.FlurlHttp.<>c.<.cctor>b__7_0()
           at System.Lazy`1.CreateValue()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Lazy`1.get_Value()
           at Flurl.Http.FlurlHttp.Configure(Action`1 configAction)
           at Flurl.Http.Testing.HttpTest..ctor()
           at BlackVueDownloader.Tests.BlackVueDownloaderTests.GetListOfFilesAndProcessTest(String ip, Int32 numRecords)
        ----- Inner Stack Trace -----
           at Interop.Http.GetSupportedFeatures()
           at System.Net.Http.CurlHandler..cctor()
      System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
    BlackVueDownloader.Tests.BlackVueDownloaderTests.GetListOfFilesAndProcessTest(ip: "192.168.1.99", numRecords: 1) [FAIL]
      ---- System.EntryPointNotFoundException : Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
      Stack Trace:
           at System.Net.Http.CurlHandler..ctor()
           at Flurl.Http.Configuration.FlurlHttpSettings.ResetDefaults()
           at Flurl.Http.FlurlHttp.<>c.<.cctor>b__7_0()
           at System.Lazy`1.CreateValue()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Lazy`1.get_Value()
    BlackVueDownloader.Tests.BlackVueDownloaderTests.CameraRespondValidTest(ip: "192.168.1.99", numRecords: 10) [FAIL]
           at Flurl.Http.FlurlHttp.Configure(Action`1 configAction)
           at Flurl.Http.Testing.HttpTest..ctor()
           at BlackVueDownloader.Tests.BlackVueDownloaderTests.GetListOfFilesAndProcessTest(String ip, Int32 numRecords)
        ----- Inner Stack Trace -----
           at Interop.Http.GetSupportedFeatures()
           at System.Net.Http.CurlHandler..cctor()
      System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
      ---- System.EntryPointNotFoundException : Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
      Stack Trace:
           at System.Net.Http.CurlHandler..ctor()
           at Flurl.Http.Configuration.FlurlHttpSettings.ResetDefaults()
           at Flurl.Http.FlurlHttp.<>c.<.cctor>b__7_0()
           at System.Lazy`1.CreateValue()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Lazy`1.get_Value()
           at Flurl.Http.FlurlHttp.Configure(Action`1 configAction)
    BlackVueDownloader.Tests.BlackVueDownloaderTests.CantFindCameraTest(ip: "192.168.1.99") [FAIL]
           at Flurl.Http.Testing.HttpTest..ctor()
           at BlackVueDownloader.Tests.BlackVueDownloaderTests.CameraRespondValidTest(String ip, Int32 numRecords)
        ----- Inner Stack Trace -----
           at Interop.Http.GetSupportedFeatures()
           at System.Net.Http.CurlHandler..cctor()
      System.TypeInitializationException : The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
      ---- System.EntryPointNotFoundException : Unable to find an entry point named 'HttpNative_GetSupportedFeatures' in DLL 'System.Net.Http.Native'.
      Stack Trace:
           at System.Net.Http.CurlHandler..ctor()
           at Flurl.Http.Configuration.FlurlHttpSettings.ResetDefaults()
           at Flurl.Http.FlurlHttp.<>c.<.cctor>b__7_0()
           at System.Lazy`1.CreateValue()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Lazy`1.get_Value()
           at Flurl.Http.FlurlHttp.Configure(Action`1 configAction)
           at Flurl.Http.Testing.HttpTest..ctor()
           at BlackVueDownloader.Tests.BlackVueDownloaderTests.CantFindCameraTest(String ip)
        ----- Inner Stack Trace -----
           at Interop.Http.GetSupportedFeatures()
           at System.Net.Http.CurlHandler..cctor()
  Finished:    BlackVueDownloader.Tests
=== TEST EXECUTION SUMMARY ===
   BlackVueDownloader.Tests  Total: 14, Errors: 0, Failed: 7, Skipped: 0, Time: 0.616s
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
vm-osx:BlackVueDownloader morrison$ 
`

I'm running with the latest:

`    "System.Net.Http": "4.1.0-rc3-24117-00"`

**Comment by kroniak** [comment]
@morrisonbrett please use Issues for this. And add code which throw exceptions.

**Comment by tmenier** [comment]
@kroniak Thanks for all your work. This is a huge PR, so please be patient with me. I'll probably take a leap of faith with some of it, I don't want to keep people waiting very long.

**Comment by tmenier** [comment]
@kroniak I see you restructured the whole solution and renamed lots of things, I hardly recognize it. :) It's all good though - it builds and all the tests pass, and I think there's lots of improvements here.

@morrisonbrett Are you going to log the issue you encountered? I'll probably wait to release a new version until that is resolved.

**Comment by morrisonbrett** [comment]
My issue may be unique to me.  Since all builds and tests pass, I'm sure it's OK.  I'll troubleshoot my project further.

**Pull request merged**
