### PR TITLE
Update DefaultUrlEncodedSerializer.cs

### PR DESCRIPTION
**Pull request by IsmailHassani**
Should solve issue #233

### CODE REVIEW

**Comment by tmenier** [comment]
Thank you. Can you provide a test that both demonstrates the bug and proves the fix?

**Comment by IsmailHassani** [comment]
Ok I will.

**Comment by IsmailHassani** [comment]
Before change:
```Test Name:	can_serialize_grant_class
Test FullName:	Flurl.Test.Http.SerializerTests.can_serialize_grant_class
Test Source:	D:\Projects\Open Source\Flurl\Test\Flurl.Test\Http\SerializerTests.cs : line 40
Test Outcome:	Failed
Test Duration:	0:00:00,026

Result StackTrace:	at Flurl.Test.Http.SerializerTests.can_serialize_grant_class() in D:\Projects\Open Source\Flurl\Test\Flurl.Test\Http\SerializerTests.cs:line 52
Result Message:	
Expected string length 127 but was 141. Strings differ at index 52.
  Expected: "...ername=user&password=password&client_id=Client_Id&client_s..."
  But was:  "...ername=user&password=password&refresh_token&client_id=Clie..."
  --------------------------------------------^

**Comment by IsmailHassani** [comment]
After change:
```Test Name:	can_serialize_grant_class
Test FullName:	Flurl.Test.Http.SerializerTests.can_serialize_grant_class
Test Source:	D:\Projects\Open Source\Flurl\Test\Flurl.Test\Http\SerializerTests.cs : line 40
Test Outcome:	Passed
Test Duration:	0:00:00,015

**Pull request closed without merging**
