### PR TITLE
Dev to master Flurl.Http 1.0.0 and Flurl 2.1.0

### PR DESCRIPTION
**Pull request by tmenier**

### CODE REVIEW

**Comment by kroniak** [comment]
I closed this PR because I want to resolve all issues before merge to master.
This is #86 #84 #83 #85.

And I make additional PR to dev.

I think master must contains only production code.

**Comment by kroniak** [comment]
Need to fix merge errors. You see commit build is OK bit PR build is failed.

**Comment by kroniak** [comment]
I think we can release 1.0.0-beta7 and 2.1.0-beta7 version to nuget from last AppVeyor build. Please do it.

We will wait any feedback from others and change code in dev if necessary.

**Comment by kroniak** [comment]
@tmenier Please bump versions to beta8.

**Comment by tmenier** [comment]
Sorry, missed your note. I think we're ok because beta7 hadn't been released until now anyway. Plus the only new breaking changes were dropping a few odd auto-gen'd methods like PatchUrlEncodedAsync.

beta7 is now on nuget, based on the latest dev build. I'll work on the release notes and make an announcement, hopefully the full release can go out within a couple days.

**Comment by tmenier** [comment]
Release notes are ready:

https://github.com/tmenier/Flurl/releases/tag/Flurl.Http.1.0.0-beta7

Let me know if you have anything to add. Note the tag. I haven't tagged or released any beta version until now. Should that be the process (tag and release to NuGet _every_ -betaX)? If so I will try to follow that going forward. When 1.0 is out of beta, I figure I'll just update the branch/tag associated with the existing release notes. Sound like the right approach?

**Comment by kroniak** [comment]
@tmenier I think that all is right.   I dont think that have to publish and tag all beta release.

**Comment by tmenier** [comment]
Great. I'm happy you've established a process and just want to make sure I follow it. I probably could have gone with -pre instead of -beta7 for nuget package, to be consistent, but oh well. Hopefully this is both the first and the last release candidate!

**Comment by tmenier** [comment]
@kroniak I think we're good to go! Any reason not to do the official release soon? If not here's my plan:

1. strip `-beta7` out of nuspecs, etc
2. update release notes (remove beta)
3. build and release both packages to nuget
4. merge dev -> master
5. announce on Twitter, etc

Am I missing anything?

**Comment by kroniak** [comment]
@tmenier 
I think
1. First remove beta7 from Flurl and commit.
2. Upload package to nuget from dev brunch PR build.
3. Rerun 1-2 for Flurl.Http
4. Fix version in package testers.
5. Merge to master.
6. Release from master both tags
7. Other actions...

**Comment by tmenier** [comment]
Sounds good. #48 might be a showstopper. (Change to API of new feature, obviously makes sense to do it now rather than introduce a breaking change later.) I'll work on it tonight.

**Comment by tmenier** [comment]
FYI, I'll release beta8 in a few hours to deal with #48. Sorry for the delay of 1.0 but I think it's for the best.

**Comment by ecentinela** [comment]
Thank you @tmenier for your efforts on the multipart and `content-type: application/json` issue!

**Comment by tmenier** [comment]
@ecentinela No problem. I'm glad you reported it. Made me re-think the whole problem I think #113 is much better that what I did originally. Hopefully you can test beta8, then we can finally go live with 1.0.

**Comment by tmenier** [comment]
we're finally here. thanks again for all the help @kroniak !

**Pull request merged**
