### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by SeanKilleen**
Supports #695.

Starting with the out of the box template commit (which of course won't work) and then tweaking it from there.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
A note: you'll likely need to specifically enable GH Actions on the PR to allow it to run.

**Comment by tmenier** [comment]
Cool, this looks like it'll fit my existing processe well. Might need to change branch name at some point based on the outcome of #710 but that'll be easy enough to do later. No need for any versioning automation here, I think that could go in a separate release-oriented workflow, along with NuGet publishing etc.

Just a couple suggested modifications:
1. How about renaming to ci.yml? (I've taken some inspiration from [AutoMapper's workflows](https://github.com/AutoMapper/AutoMapper/tree/master/.github/workflows), they seem to run a very tight ship overall.)
2. I'm thinking let's be bold and delete all AppVeyor-related bits right out of the gates, including the entire `/build` folder. I don't _think_ any of it will be needed, but if I'm wrong, well, that's what version control is for. 😄 

Thanks again!

**Comment by SeanKilleen** [comment]
@tmenier 

>  No need for any versioning automation here, I think that could go in a separate release-oriented workflow, along with NuGet publishing etc.

Sure -- happy to do that here or in a follow-up. Since you're looking at GitHub flow and a main branch + releases, you may want to either:

* Tag releases manually with a version number and have the release workflow triggered on a tag being created with a certain specification
* Or if you're feeling bold, you _could_ do an auto-release via working something like [Minver](https://github.com/adamralph/minver) into your package. Every commit to main that comes between your tagged releases could then be published as a pre-release package.

But if you're happy to do that as a later step, I'm happy to leave it be for now 👍 

> How about renaming to ci.yml

Sure, I've got no hang-ups on names and that seems reasonable enough.

> I'm thinking let's be bold and delete all AppVeyor-related bits right out of the gates, including the entire /build folder.

You've got it! Normally I do those in separate PRs because I like seeing the build pass before merging. 😆 However I'll do that right now.

**Comment by SeanKilleen** [comment]
Alright, changes made per suggestions -- happy to do more beyond this, just tag me with any input/needs you have!

**Comment by SeanKilleen** [comment]
@tmenier I think you may need to allow GitHub Actions to run on this -- I can see it on my local, but not on this one. I think there may be a few failures to address and I'd like to see them here so I can review them with you if they happen.

**Comment by tmenier** [comment]
Sorry I've disappeared for a while, I have a bad habit of doing that when life gets busy. This is still very much on my radar and I hope to get to it merged in conjunction with some other work related to #710 very soon. Thanks again!

**Pull request merged**
