### PR TITLE
Refactoring - PART 2 - code cleanup

### PR DESCRIPTION
**Pull request by kroniak**
Code cleanup #82 to remove any build warnings.

1. Added missing XML tags
2. Added needed xml for exceptions
3. Misc code cleanup.
4. Build scripts refactored to minimize and clean output.

### CODE REVIEW

**Comment by kroniak** [comment]
Build and tests are passed.

**Comment by tmenier** [comment]
Great!

Notes to self:
* Tweak FlurlEventType enum comments
* "The inner." -> "The inner exception."
* "The client." & "The Flurl client." -> "The FlurlClient."

**Comment by kroniak** [comment]
@tmenier please push it to refactoring_PART_2_code_cleanup branch

**Comment by kroniak** [comment]
I done all that I wished.

**Pull request merged**
