### PR TITLE
Added NETCore libraries, build cmd, nuget packages

### LINKED ISSUE #61: Support for .NET Core
Are there any plans to support .net core? I'm using Flurl.Http with ASP.NET 5 and it says Flurl does not support DnxCore5.0

### PR DESCRIPTION
**Pull request by kroniak**
@tmenier  Simple fix #61 

I have seen that you declined a PR with many changes of code.
I have added one X project to solution which compiles shared code.
Cmd in ./build folder produces a valid nuget package with name [Flurl.Http.NETCore](https://www.nuget.org/packages/Flurl.Http.NETCore/) with NET45+, NETCore, PCL and etc. frameworks.

Or do you want to build nuget yourself? You can to include outputs to your nuget spec file into Flurl.Http package.

### CODE REVIEW

**Comment by kroniak** [comment]
In last commit https://github.com/tmenier/Flurl/pull/64/commits/41f6b03889777a982d2a8bbc49ae4ea8cd64c914

[edit] version of package
[edit] target framework to .NET Platform Standard 1.0. (NET45+, NETCore, other targets) Full list https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

Now I am working on support PCL target in same X proj. Result will be one X proj to all targets that you was supporting earlier.

**Comment by kroniak** [comment]
@tmenier simple fix #61 was done by commits in this PR.

Next.
If you agree I can refactor both package to NET Platform 1.0 + PCL.
The result will be:
- X proj "Flurl" (ver. 1.1.0) with targets NET Platform 1.0 + PCL => auto build nuget
- X proj "Flurl.Http" (0.8.0) depends on Flurl (1.10) with same targets with => auto build nuget
- Shared Code Project "Flurl.Shared" for testing. 

Write me about your opinion. Have a nice day.

**Comment by tmenier** [comment]
Thank you for this. I'm just getting caught up on some things. I have some minor refactorings that have been pending for a while that I'll get pushed first, then look at your stuff (PR + NuGet package)

I am still getting up to speed on .NET Core in general (haven't needed it yet) so there's a small learning curve for me but what you've done looks promising. My top priority is to make it as easy as possible for devs to use Flurl, including the decision (or lack thereof) of which NuGet package to choose. If "all" platforms/delivery methods (Framework 4+, PCL, Core) can be accommodated with a single NuGet package (Flurl.Http), that is ideal. If that is what you're suggesting doing, I am 100% on board. Thanks again.

**Comment by kroniak** [comment]
OK. We will wait for your minor changes. After that we can continue with PR with growing up versions on packages (include new *.NETCore packages)

There are a problem with combinating all platforms in one package with PCL. Nuget package was created with section "framework assembles" only for portable targets, but VS tries apply it to all target (NET Platform 1.0). You can view it on package https://www.nuget.org/packages/Flurl.Http.NETCore/0.7.1. May be you can assist me with that.

**Comment by tmenier** [comment]
The minor refactorings I mentioned have been pushed. Time for me to get up to speed on .NET Core. My initial thought is, if Json.NET only has 1 nuget package and it works with both Flurl packages, why do we need 2 Flurl packages?

I see they're having their share of headaches over this too:
https://github.com/JamesNK/Newtonsoft.Json/issues/618

**Comment by kroniak** [comment]
**Work is done.**

**Summary**: netcore dll pack into exist packages with bump versions.

**Changes**:
- [update] nuget.exe to produce NET Platform 5.4 target packages.
- [added] 2 xprojects for NET Platform 5.4 which compiles shared code.
- [added] publish.cmd. It auto builds packages on postbuild trigger.
- [edit] projects files to use publish.cmd

I have tested packages on DNX projects, classic lib, portable lib.  
I am attaching both nuget files to review.
[Publish.zip](https://github.com/tmenier/Flurl/files/200828/Publish.zip)

**Comment by tmenier** [comment]
This will merge cleanly with my recent changes, so I'm not worried about that. One request though - could you take a look at your line endings and make sure they're consistent with mine? I think they are different and that's making it really difficult to review the diff:

https://github.com/tmenier/Flurl/pull/64/files

Some tips here that might be helpful:

https://help.github.com/articles/dealing-with-line-endings/

Thanks!

**Comment by kroniak** [comment]
@tmenier I have fixed eols and added .gitattribute file to prevent that situation for future.

**Comment by kroniak** [comment]
I have squashed commits and created final PR #69

**Pull request closed without merging**
