### PR TITLE
URL fragment support

### PR DESCRIPTION
**Pull request by mgyongyosi**
Fix for #29

URL fragment support added.
Changed Url class' ctor to use regexp instead of string splitting.
Tests included.

### CODE REVIEW

**Comment by tmenier** [comment]
Thank you!

**Comment by tmenier** [comment]
I'd like to package up a NuGet release this week with your enhancement (thanks again). I'm just curious - did you find the regex online somewhere? I just want to make sure I understand it thoroughly as this could be a breaking change.

**Comment by mgyongyosi** [comment]
Nope, I have created the regex and it slices the the url into three parts:

- 1st capturing group ([^?#\n]*) selects everything until a '?', '#' or newline character (it can be used in multinline mode;currently it does not matter, because it does use the regex in singleline mode)
- 2nd capturing group ([^#\n]*) selects everything until a '#' or newline character (it can be used in multinline mode; currently it does not matter, because it does use the regex in singleline mode)
- 3rd capturing group (.*) selects everything until the end of the string

I hope it is clearer now. :)

**Comment by tmenier** [comment]
Thanks! I completely get it now.

I'd like to trim the `#` off the fragment because strictly speaking it's part of the fragment. I'm also introducing a Query property that returns the entire query as a string, and the `?` needs to be trimmed off of that. Do you think it's better/more readable to leave the regex alone and do it after, like this?

````C#
var urlParts = Regex.Match(baseUrl, URL_SLICE_REGEXP, RegexOptions.IgnoreCase | RegexOptions.Singleline);
Path = urlParts.Groups[1].Value;
Query = urlParts.Groups[2].Value.TrimStart('?');
Fragment = urlParts.Groups[3].Value.TrimStart('#');
````

Also, we _could_ avoid the regex (and therefore the dependency on System.Text.RegularExpressions) like this:

 ````C#
var parts = baseUrl.Split(new[] { '#' }, 2);
Fragment = (parts.Length == 2) ? parts[1] : "";
parts = parts[0].Split(new[] { '?' }, 2);
Query = (parts.Length == 2) ? parts[1] : "";
Path = parts[0];
````

Thoughts? I'm on the fence about whether to keep the regex dependency when it's fairly easy to go without it.

**Comment by mgyongyosi** [comment]
Yep, I agree with you! I have read again the RFC 3986 and W3C's documentation (https://dev.w3.org/html5/spec-LC/urls.html#parsing-urls) ont the fragment handling and what you suggest is the right solution (trimming of the ? and #).

On avoiding regular expression: it s only my personal preference to use regex instead of string splitting, for me regex is clearer, but your solution is right also and without dependency. 

Choice is yours :)

**Pull request merged**
