### PR TITLE
This fix #74

### LINKED ISSUE #74: Flurl v1.1.1/Flurl.Http v0.8.0 Broken on .Net v4.6.1
I'm starting a new project for which we're going to be using Visual Studio 2015 and targeting version 4.6.1 of the .Net Framework. It appears that Flurl has released a new version to Nuget (Flurl v1.1.1/Flurl.Http v0.8.0) that supports the DotNet Core bits. Unfortunately, the new version would seem to be broken with respect to .Net v4.6.1. A simple program like this:

    using Flurl;
    using Flurl.Http;
    . . .
    Task<Stream> request = "https://www.google.com/"
                           .SetQueryParam( "q" , "foobar" )
                           .GetStreamAsync()
                           ;
    . . .

compiles just fine in a .Net 4.5.2 project. Put it in a .Net 4.6.1 project and you get a compile error:

    ...\flurl-bug\dotnet-461\Program.cs(17,36,19,51):
    error CS0012: The type 'Url' is defined in an assembly that
    is not referenced. You must add a reference to assembly
    'Flurl, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.

Here's my Github repo with code to reproduce the issue: https://github.com/nbcarey/flurl-bug.

Diffing the two `*.csproj` files, it look like for the .Net 4.5.2 project, Nuget adds a reference to this assembly (the one I would expect to see):

    <Reference Include="Flurl, Version=1.1.1.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Flurl.1.1.1\lib\portable-net40+sl50+win+wpa81+wp80+MonoAndroid10+MonoTouch10\Flurl.dll</HintPath>
      <Private>True</Private>
    </Reference>

But the .Net 4.6.1 project gets a reference to a completely different assembly (one that I would *not* expect to see):

    <Reference Include="Flurl.NETCore, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Flurl.1.1.1\lib\dotnet5.4\Flurl.NETCore.dll</HintPath>
      <Private>True</Private>
    </Reference>

While I suspect that I can fix the problem be to revert to the older version in Nuget, but it would be nice to get this fixed.

### PR DESCRIPTION
**Pull request by kroniak**
This close #74. 

Problem was in package name, mini refactoring.

After NETCORE RC2 released need to refactor targets to "netcoreapp". There are in MAY.

### CODE REVIEW

**Comment by kroniak** [comment]
[Links to packages](https://onedrive.live.com/redir?resid=C645BE6419A31FCC!13989&authkey=!AGBjnN082TTTywI&ithint=folder%2c)

**Comment by tmenier** [comment]
Thanks!

**Comment by tmenier** [comment]
I was in the middle of some stuff in master related to #66 (probably should have branched). That's all sorted out and new prerelases of both packages are up. Looking good - I will probably strip the "-pre" later today if I don't hear of any issues. Thanks again.

**Comment by tmenier** [comment]
Full release done.

**Comment by kroniak** [comment]
@tmenier cool!

**Pull request merged**
