### PR TITLE
Feature/add coverage

### PR DESCRIPTION
**Pull request by kroniak**
Added code coverage tools, updated scripts for coverage

### CODE REVIEW

**Comment by kroniak** [comment]
please dont merge. Pipeline test scripts failed but pipeline is OK. This problem was since https://ci.appveyor.com/project/kroniak/flurl/builds/21743257

**Comment by kroniak** [comment]
@tmenier please fix failed test

**Comment by kroniak** [comment]
@tmenier I have fix pipeline. About 2 months it was invalid =)

**Comment by tmenier** [comment]
@kroniak Sorry it took me so long to get to this. I'll merge first and then fix the test.

One question. I know AppVeyor can discover and run tests automatically, and the results show up [here](https://ci.appveyor.com/project/kroniak/flurl/build/tests). I noticed we're using a custom test script (and the results do not show up in the Tests tab). Is there anything unusual about our build that requires testing to be configured in a "non-standard" way? I'm just wondering if it can be simplified.

**Comment by kroniak** [comment]
@ this way is right for situation when we want to do anything with tests. Example count code coverage. And for me and other Mac users using test.sh for test executing is right way. 

PS On my environment in mac this test are failed too.

**Comment by tmenier** [comment]
Ok thanks. The test is "fixed" on AppVeyor (I hope). Can you try it locally? It's a weird test involving multithreading and artificial delays. Always passed for me locally. The delays seemed long enough to make sure things happen in a specific order, but when I made them even longer I finally hit a point where they pass on AppVeyor.

Hopefully a 5-second test isn't too annoying, but if it's still not reliable I might just drop it. It's not very important - basically all it does is make sure a `lock` works. :)

**Comment by kroniak** [comment]
@tmenier 
```bash
 kroniak  ~  Workspaces  _lab  Flurl   dev  ./Build/test.sh 
!!WARNING!! This script for pipeline test running and checking code coverage for netstandard and netcoreapp targets
Build started, please wait...
Build completed.

Test run for /Users/kroniak/Workspaces/_lab/Flurl/test/Flurl.Test/bin/Release/netcoreapp2.0/Flurl.Test.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   can_download_file("https://httpbin.org/anything/foo%3Fbar%3Ading",null,null,"foo_bar_ding")
Error Message:
   String lengths are both 109. Strings differ at index 100.
  Expected: ".../flurl-test-e6150ed3-96a2-4afb-a4bd-0d2e77dbc997/foo_bar_ding"
  But was:  ".../flurl-test-e6150ed3-96a2-4afb-a4bd-0d2e77dbc997/foo?bar:ding"
  ------------------------------------------------------------------^

Stack Trace:
   at Flurl.Test.Http.RealHttpTests.<can_download_file>d__2.MoveNext() in /Users/kroniak/Workspaces/_lab/Flurl/Test/Flurl.Test/Http/RealHttpTests.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

Skipped  can_use_response_queue_in_parallel
Skipped  can_set_query_params_from_kv_pairs

Total tests: 294. Passed: 291. Failed: 1. Skipped: 2.
Test Run Failed.
Test execution time: 16.5431 Seconds
```

**Pull request merged**
